configFactory:
    className: Nest\Config\ConfigFactory

cookies:
    className:  Phalcon\Http\Response\Cookies

dispatcher:
    className: Nest\Mvc\Dispatcher

escaper:
    className:  Phalcon\Escaper

eventsManager:
    className:  Phalcon\Events\Manager

registry:
    className: Nest\Registry

request:
    className: Phalcon\Http\Request

response:
    className: Phalcon\Http\Response

router:
    className: Phalcon\Mvc\Router
    arguments: [false]

routingParser:
    className: Nest\Mvc\Router\RoutingParser

session:
    className:  Phalcon\Session\Adapter\Files
    calls:
        - [start]

url:
    className: Phalcon\Mvc\Url

view:
    className: Phalcon\Mvc\View